### ISSUE TITLE
meta name vs meta property

### ISSUE THREAD

**Issue by rogue-syntax** [samholmes/node-open-graph#6]
I had to change the first few lines of the metaTags.each iteration to also catch meta tags with the open-graph data under the 'name' attribute instead of 'property' attribute. I don't know how common this is but it seems to come up (http://teamcoco.com for example).

I changed this:

```
    var element = $(this);
        propertyAttr = element.attr('property');

    // If meta element isn't an "og:" property, skip it
    if (!propertyAttr || propertyAttr.substring(0, namespace.length) !== namespace)
        return;

    var property = propertyAttr.substring(namespace.length+1),
        content = element.attr('content');
```

to this:

```
    var element = $(this);
    propAttr = element.attr('property');
    nameAttr = element.attr('name');

        if ((!propAttr || propAttr.substring(0, namespace.length) !== namespace) && (!nameAttr || nameAttr.substring(0, namespace.length) !== namespace) ) 
        return;

        if( !propAttr || propAttr.substring(0, namespace.length) !== namespace ){
            propertyAttr = nameAttr;
        } else if( !nameAttr || nameAttr.substring(0, namespace.length) !== namespace  ){
            propertyAttr = propAttr;
        } else {
            return;
        }
```

..more or less. I'm not sure if this is the right thing to do, but feel free to incorporate something like this if it is the right thing to do.

**Comment by samholmes** [comment]
If I understand correctly, you're saying that some sites (e.g. teamcoco.com) will use the name attribute instead of the property attribute for the meta element in order to define the open-graph property key? For example, instead of:

    <meta property="og:title" content="Yew!">

a site will use:

    <meta name="og:title" content="Yew!">

Sure a site might do this, but the open graph protocol doesn't say anything about the name attribute being an alternative to the property attribute: http://ogp.me/ AFAIK

**Comment by samholmes** [comment]
![screen shot 2016-11-11 at 3 30 45 pm](https://cloud.githubusercontent.com/assets/517469/20233381/dfb77bb6-a823-11e6-9957-68b4d35a52f2.png)

Looks like teamcoco.com doesn't use the name attribute as an alternative to property.

Even if a random site decides to go against the standard, this module should follow the open graph protocol standard and not deviate in order to appease to a rare case.
